### ISSUE TITLE
erreur échelle automatique

### ISSUE THREAD

**Issue by infoble** [LCacheux68224/Thematic#1]
Bonjour,
pour info voici l'erreur que j'ai lorsque le champ "polygon layer for an automatique scale" est renseigné et que je ne coche pas "extented analysis" :

> Échelle automatique
> Traceback (most recent call last):
> File "C:/Users/jacques-b/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Thematic-master\CirclesAlgorithms.py", line 392, in processAlgorithm
> feedback.pushInfo(self.tr(' • Val_Max : {0}'.format(val1)))
> UnboundLocalError: local variable 'val1' referenced before assignment

le script ne fonctionne qu'avec "extented analysis".

Lorsque les champ "polygon layer for an automatique scale" n'est pas renseigné j'ai l'erreur suivante dans tous les cas :

> Traceback (most recent call last):
> File "C:/Users/jacques-b/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Thematic-master\CirclesAlgorithms.py", line 345, in processAlgorithm
> radiusFormula = '2*sqrt(abs({0})*{1}/(7*pi()*{2}))'.format(stockValue, layerArea, summary['SUM'])
> UnboundLocalError: local variable 'layerArea' referenced before assignment

J'imagine que dans l'avenir il sera également possible de personnaliser l'échelle...
Merci encore pour votre travail.

**Comment by LCacheux68224** [comment]
Bonjour et merci pour ce retour.
Il y a en effet encore pas mal de travail à faire sur l'extension et toutes les fonctionnalités ne sont pas encore présente. En particulier, la cohérence des paramètres renseignés n'est pas encore vérifier.
La personnalisation de l'échelle est bien évidemment prévue.
